// Warning: generated file; your changes could be lost when a new file is generated.
#r @"..\..\Endorphin.Core\bin\Debug\Endorphin.Core.dll"
#r @"..\..\Endorphin.Instrument.KeysightRfSource\bin\Debug\Endorphin.Instrument.KeysightRfSource.dll"
#r @"..\..\packages\log4net.2.0.3\lib\net40-full\log4net.dll"
#r @"System.dll"
#r @"System.Core.dll"
#r @"System.Drawing.dll"
#r @"System.Numerics.dll"
#r @"System.Windows.Forms.dll"
#r @"System.Xml.dll"
#r @"..\..\..\..\..\..\..\Program Files (x86)\National Instruments\MeasurementStudioVS2012\DotNET\Assemblies\Current\NationalInstruments.VisaNS.dll"
#r @"..\..\packages\NUnitTestAdapter.2.0.0\lib\nunit.core.dll"
#r @"..\..\packages\NUnitTestAdapter.2.0.0\lib\nunit.core.interfaces.dll"
#r @"..\..\packages\NUnit.2.6.4\lib\nunit.framework.dll"
#r @"..\..\packages\NUnitTestAdapter.2.0.0\lib\nunit.util.dll"
#r @"..\..\packages\NUnitTestAdapter.2.0.0\lib\NUnit.VisualStudio.TestAdapter.dll"