// Warning: generated file; your changes could be lost when a new file is generated.
#load @"load-references.fsx"
#load @"..\Model.fs"
      @"..\Quantities.fs"
      @"..\IO.fs"
      @"..\Basic.fs"
      @"..\Triggering.fs"
      @"..\Source.fs"
      @"..\Modulation.fs"
      @"..\Sweep.fs"
      @"..\RfSource.fs"
      @"..\DummyInstrument.fs"
