// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load @"load-references.fsx"
#load @"..\Model.fs"
      @"..\InternalModel.fs"
      @"..\Parsing.fs"
      @"..\IO.fs"
      @"..\CRC.fs"
      @"..\Basic.fs"
      @"..\Triggering.fs"
      @"..\Source.fs"
      @"..\Modulation.fs"
      @"..\Sweep.fs"
      @"..\Waveform.fs"
      @"..\RfPulse.fs"
      @"..\RfSource.fs"
